<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';

$action=(string)($_GET['action']??'state');
function addlg_find(array $items,string $id):?array{foreach($items as $x)if((string)($x['id']??'')===$id)return$x;return null;}
function addlg_primary_id(array $state):string{return (string)($state['character']['id']??'speaker_primary');}
function addlg_legacy_voice(array $state):array{
  $v=is_array($state['voice_memory']??null)?$state['voice_memory']:[];
  return ['name'=>(string)($v['name']??($state['character']['name']??'Main character')),'description'=>(string)($v['description']??''),'language'=>(string)($v['language']??'en'),'delivery_rules'=>(string)($v['delivery_rules']??''),'reference'=>is_array($v['reference']??null)?$v['reference']:null];
}
function addlg_cast(array $state):array{
  $out=[];$char=is_array($state['character']??null)?$state['character']:null;
  if($char){$master=$char['references']['master_front']??$char['asset']??null;$out[]=['id'=>(string)$char['id'],'name'=>(string)($char['name']??'Main character'),'description'=>(string)($char['description']??''),'primary'=>true,'identity_reference'=>is_array($master)?$master:null,'voice'=>addlg_legacy_voice($state)];}
  foreach((array)($state['cast']??[]) as $m){if(!is_array($m))continue;$voice=is_array($m['voice']??null)?$m['voice']:[];$out[]=['id'=>(string)($m['id']??ad_id('cast')),'name'=>(string)($m['name']??'Character'),'description'=>(string)($m['description']??''),'primary'=>false,'identity_reference'=>is_array($m['identity_reference']??null)?$m['identity_reference']:null,'voice'=>['name'=>(string)($voice['name']??($m['name']??'Character')),'description'=>(string)($voice['description']??''),'language'=>(string)($voice['language']??'en'),'delivery_rules'=>(string)($voice['delivery_rules']??''),'reference'=>is_array($voice['reference']??null)?$voice['reference']:null]];}
  return $out;
}
function addlg_speaker(array $state,string $id):?array{foreach(addlg_cast($state)as$m)if((string)$m['id']===$id)return$m;return null;}
function addlg_download_audio(string $url,string $id):?array{
  if(!preg_match('#^https://#i',$url))return null;$relative='storage/references/'.preg_replace('/[^A-Za-z0-9_-]/','_',$id).'.mp3';$dest=AD_ROOT.'/'.$relative;
  $ch=curl_init($url);$fh=fopen($dest,'wb');if(!$ch||!$fh)return null;$written=0;curl_setopt_array($ch,[CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>4,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>180,CURLOPT_WRITEFUNCTION=>static function($ch,string$data)use($fh,&$written):int{$written+=strlen($data);if($written>40*1024*1024)return 0;return fwrite($fh,$data)?:0;}]);$ok=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$type=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);fclose($fh);if(!$ok||$code<200||$code>=300||$written<128){@unlink($dest);return null;}return ['id'=>ad_id('ref'),'kind'=>'audio','role'=>'voice','path'=>$relative,'url'=>ad_public_media_url($relative),'mime'=>$type?:'audio/mpeg','bytes'=>$written,'original_name'=>'dialogue.mp3','created_at'=>ad_now()];
}
function addlg_store_speaker(array $state,string $speakerId,array $fields):array{
  $primary=addlg_primary_id($state);
  if($speakerId===$primary){$v=addlg_legacy_voice($state);foreach(['name','description','language','delivery_rules']as$k)if(array_key_exists($k,$fields))$v[$k]=ad_substr(trim((string)$fields[$k]),0,in_array($k,['description','delivery_rules'],true)?1200:120);$v['id']='voice_'.$primary;$v['updated_at']=ad_now();$state['voice_memory']=$v;return $state;}
  foreach($state['cast'] as &$m)if((string)($m['id']??'')===$speakerId){foreach(['name','description']as$k)if(array_key_exists($k,$fields))$m[$k]=ad_substr(trim((string)$fields[$k]),0,$k==='description'?1200:120);$v=is_array($m['voice']??null)?$m['voice']:[];foreach(['voice_name'=>'name','voice_description'=>'description','language'=>'language','delivery_rules'=>'delivery_rules']as$src=>$dst)if(array_key_exists($src,$fields))$v[$dst]=ad_substr(trim((string)$fields[$src]),0,in_array($dst,['description','delivery_rules'],true)?1200:120);$m['voice']=$v;$m['updated_at']=ad_now();break;}unset($m);return $state;
}
try{
  if($action==='state'){$s=ad_state_read();ad_json(['ok'=>true,'cast'=>addlg_cast($s),'configured'=>ad_mock_mode()||ad_env('RUNWAY_API_KEY')!=='']);}
  if($action==='add-speaker'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$name=ad_substr(trim((string)($d['name']??'')),0,120);if($name==='')ad_json(['ok'=>false,'error'=>'Character name is required.'],422);$member=['id'=>ad_id('cast'),'name'=>$name,'description'=>ad_substr(trim((string)($d['description']??'')),0,1200),'identity_reference'=>null,'voice'=>['name'=>$name,'description'=>'','language'=>'en','delivery_rules'=>'','reference'=>null],'created_at'=>ad_now(),'updated_at'=>ad_now()];$next=ad_state_mutate(function(array$s)use($member):array{$cast=array_values(array_filter((array)($s['cast']??[]),'is_array'));$cast[]=$member;$s['cast']=array_slice($cast,-12);return$s;});ad_json(['ok'=>true,'member'=>addlg_speaker($next,$member['id']),'cast'=>addlg_cast($next)]);}
  if($action==='save-speaker'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$id=trim((string)($d['speaker_id']??''));$s=ad_state_read();if(!addlg_speaker($s,$id))ad_json(['ok'=>false,'error'=>'Speaker not found.'],404);$next=ad_state_mutate(fn(array$x):array=>addlg_store_speaker($x,$id,$d));ad_json(['ok'=>true,'speaker'=>addlg_speaker($next,$id),'cast'=>addlg_cast($next)]);}
  if($action==='upload-speaker-reference'&&$_SERVER['REQUEST_METHOD']==='POST'){$speakerId=trim((string)($_POST['speaker_id']??''));$type=(string)($_POST['type']??'identity');$s=ad_state_read();if(!addlg_speaker($s,$speakerId))ad_json(['ok'=>false,'error'=>'Speaker not found.'],404);if(empty($_FILES['reference']))ad_json(['ok'=>false,'error'=>'Reference file is required.'],422);$asset=ad_store_director_reference($_FILES['reference']);if($type==='voice'){if(($asset['kind']??'')!=='audio')ad_json(['ok'=>false,'error'=>'Voice reference must be audio.'],422);$asset['role']='voice';$asset['speaker_id']=$speakerId;}else{if(($asset['kind']??'')!=='image')ad_json(['ok'=>false,'error'=>'Character identity reference must be an image.'],422);$asset['role']='character';$asset['speaker_id']=$speakerId;}
    $next=ad_state_mutate(function(array$x)use($speakerId,$type,$asset):array{$primary=addlg_primary_id($x);if($speakerId===$primary){if($type==='voice'){$v=addlg_legacy_voice($x);$v['reference']=$asset;$v['updated_at']=ad_now();$x['voice_memory']=$v;}return$x;}foreach($x['cast']as&$m)if(($m['id']??'')===$speakerId){if($type==='voice'){$v=is_array($m['voice']??null)?$m['voice']:[];$v['reference']=$asset;$m['voice']=$v;}else$m['identity_reference']=$asset;$m['updated_at']=ad_now();break;}unset($m);return$x;});ad_json(['ok'=>true,'speaker'=>addlg_speaker($next,$speakerId),'cast'=>addlg_cast($next)]);}
  if($action==='save-line'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$shotId=trim((string)($d['shot_id']??''));$text=ad_substr(trim((string)($d['text']??'')),0,1800);if($text==='')ad_json(['ok'=>false,'error'=>'Dialogue text is required.'],422);$s=ad_state_read();$speakerId=trim((string)($d['speaker_id']??addlg_primary_id($s)));$speaker=addlg_speaker($s,$speakerId);if(!$speaker)ad_json(['ok'=>false,'error'=>'Choose a valid speaker.'],422);$voice=$speaker['voice'];$line=['id'=>ad_id('dialogue'),'speaker_id'=>$speakerId,'speaker_name'=>(string)$speaker['name'],'text'=>$text,'delivery'=>ad_substr(trim((string)($d['delivery']??'')),0,500),'language'=>ad_substr(trim((string)($d['language']??($voice['language']??'en'))),0,20),'audio_reference'=>null,'created_at'=>ad_now(),'updated_at'=>ad_now()];$next=ad_state_mutate(function(array$x)use($shotId,$line):array{foreach($x['shots']as&$sh)if(($sh['id']??'')===$shotId){$lines=is_array($sh['dialogue']??null)?$sh['dialogue']:[];$lines[]=$line;$sh['dialogue']=array_slice($lines,-24);$ids=array_values(array_unique(array_filter(array_map(static fn($l)=>(string)($l['speaker_id']??''),$sh['dialogue']))));$sh['speaker_ids']=$ids;$sh['updated_at']=ad_now();break;}unset($sh);return$x;});ad_json(['ok'=>true,'shot'=>addlg_find($next['shots'],$shotId),'line'=>$line]);}
  if($action==='generate-speech'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$shotId=trim((string)($d['shot_id']??''));$lineId=trim((string)($d['line_id']??''));$s=ad_state_read();$shot=addlg_find($s['shots'],$shotId);if(!$shot)ad_json(['ok'=>false,'error'=>'Shot not found.'],404);$line=addlg_find((array)($shot['dialogue']??[]),$lineId);if(!$line)ad_json(['ok'=>false,'error'=>'Dialogue line not found.'],404);$speakerId=(string)($line['speaker_id']??addlg_primary_id($s));$speaker=addlg_speaker($s,$speakerId);if(!$speaker)ad_json(['ok'=>false,'error'=>'Dialogue speaker no longer exists.'],409);$voice=$speaker['voice'];$prompt=trim(((string)($line['delivery']??'')!==''?'Delivery: '.$line['delivery'].'. ':'').((string)($voice['delivery_rules']??'')!==''?'Voice rules: '.$voice['delivery_rules'].'. ':'').(string)$line['text']);
    if(ad_mock_mode()){$asset=['id'=>ad_id('ref'),'kind'=>'audio','role'=>'voice','speaker_id'=>$speakerId,'speaker_name'=>$speaker['name'],'path'=>'','url'=>'','mime'=>'audio/mpeg','bytes'=>0,'original_name'=>'mock-dialogue.mp3','created_at'=>ad_now()];$next=ad_state_mutate(function(array$x)use($shotId,$lineId,$asset):array{foreach($x['shots']as&$sh)if(($sh['id']??'')===$shotId){foreach($sh['dialogue']as&$ln)if(($ln['id']??'')===$lineId){$ln['audio_reference']=$asset;$ln['speech_status']='completed';break;}unset($ln);$refs=is_array($sh['references']??null)?$sh['references']:[];$refs[]=$asset;$sh['references']=array_slice($refs,-20);break;}unset($sh);return$x;});ad_json(['ok'=>true,'done'=>true,'shot'=>addlg_find($next['shots'],$shotId)]);}
    $key=ad_env('RUNWAY_API_KEY');if($key==='')ad_json(['ok'=>false,'error'=>'RUNWAY_API_KEY is not configured.'],409);$payload=['model'=>'seed_audio','promptText'=>$prompt,'outputFormat'=>'mp3'];$vr=$voice['reference']??null;if(is_array($vr)&&!empty($vr['url'])){ad_require_live_public_https_url((string)$vr['url']);$payload['voice']=['type'=>'reference-audio','audioUri'=>(string)$vr['url']];}$resp=ad_http_json('POST','https://api.dev.runwayml.com/v1/text_to_speech',['Authorization: Bearer '.$key,'Content-Type: application/json','X-Runway-Version: 2024-11-06'],$payload);$taskId=(string)($resp['id']??'');if($taskId==='')throw new RuntimeException('Runway returned no speech task id.');ad_state_mutate(function(array$x)use($shotId,$lineId,$taskId):array{foreach($x['shots']as&$sh)if(($sh['id']??'')===$shotId){foreach($sh['dialogue']as&$ln)if(($ln['id']??'')===$lineId){$ln['speech_task_id']=$taskId;$ln['speech_status']='submitted';break;}unset($ln);break;}unset($sh);return$x;});ad_json(['ok'=>true,'task_id'=>$taskId,'done'=>false]);}
  if($action==='poll-speech'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$shotId=trim((string)($d['shot_id']??''));$lineId=trim((string)($d['line_id']??''));$s=ad_state_read();$shot=addlg_find($s['shots'],$shotId);$line=$shot?addlg_find((array)($shot['dialogue']??[]),$lineId):null;if(!$line)ad_json(['ok'=>false,'error'=>'Dialogue line not found.'],404);$taskId=(string)($line['speech_task_id']??'');if($taskId==='')ad_json(['ok'=>false,'error'=>'Speech task id missing.'],409);$key=ad_env('RUNWAY_API_KEY');$resp=ad_http_json('GET','https://api.dev.runwayml.com/v1/tasks/'.rawurlencode($taskId),['Authorization: Bearer '.$key,'X-Runway-Version: 2024-11-06']);$status=strtoupper((string)($resp['status']??'PENDING'));if($status==='FAILED')ad_json(['ok'=>false,'error'=>(string)($resp['failure']??'Speech generation failed.')],502);if($status!=='SUCCEEDED')ad_json(['ok'=>true,'done'=>false,'status'=>strtolower($status)]);$out=$resp['output']??[];$url=is_array($out)?(string)($out[0]??''):'';$asset=$url!==''?addlg_download_audio($url,$taskId):null;if(!$asset)ad_json(['ok'=>false,'error'=>'Speech completed but audio could not be saved.'],502);$speakerId=(string)($line['speaker_id']??addlg_primary_id($s));$speaker=addlg_speaker($s,$speakerId);$asset['speaker_id']=$speakerId;$asset['speaker_name']=(string)($speaker['name']??'Speaker');$next=ad_state_mutate(function(array$x)use($shotId,$lineId,$asset):array{foreach($x['shots']as&$sh)if(($sh['id']??'')===$shotId){foreach($sh['dialogue']as&$ln)if(($ln['id']??'')===$lineId){$ln['audio_reference']=$asset;$ln['speech_status']='completed';$ln['updated_at']=ad_now();break;}unset($ln);$refs=is_array($sh['references']??null)?$sh['references']:[];$refs[]=$asset;$sh['references']=array_slice($refs,-20);$sh['updated_at']=ad_now();break;}unset($sh);return$x;});ad_json(['ok'=>true,'done'=>true,'shot'=>addlg_find($next['shots'],$shotId),'reference'=>$asset]);}
  ad_json(['ok'=>false,'error'=>'Unknown dialogue action.'],404);
}catch(Throwable$e){ad_json(['ok'=>false,'error'=>ad_substr($e->getMessage(),0,400)],500);}
