<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';

$action=(string)($_GET['action']??'state');
function adsnd_find(array $items,string $id):?array{foreach($items as $x)if(is_array($x)&&(string)($x['id']??'')===$id)return$x;return null;}
function adsnd_scene_plan(array $scene):array{$p=is_array($scene['sound_design']??null)?$scene['sound_design']:[];return ['ambience_prompt'=>ad_substr(trim((string)($p['ambience_prompt']??'')),0,1200),'music_prompt'=>ad_substr(trim((string)($p['music_prompt']??'')),0,1200),'music_behavior'=>ad_substr(trim((string)($p['music_behavior']??'')),0,500),'mix_notes'=>ad_substr(trim((string)($p['mix_notes']??'')),0,1000),'ambience_asset'=>is_array($p['ambience_asset']??null)?$p['ambience_asset']:null,'music_asset'=>is_array($p['music_asset']??null)?$p['music_asset']:null,'jobs'=>array_values(array_filter((array)($p['jobs']??[]),'is_array'))];}
function adsnd_shot_plan(array $shot):array{$p=is_array($shot['sound_design']??null)?$shot['sound_design']:[];return ['cues'=>array_values(array_filter((array)($p['cues']??[]),'is_array')),'mix_notes'=>ad_substr(trim((string)($p['mix_notes']??'')),0,1000)];}
function adsnd_download(string $url,string $id):?array{if(!preg_match('#^https://#i',$url))return null;$relative='storage/references/'.preg_replace('/[^A-Za-z0-9_-]/','_',$id).'.mp3';$dest=AD_ROOT.'/'.$relative;$ch=curl_init($url);$fh=fopen($dest,'wb');if(!$ch||!$fh){if($fh)fclose($fh);if($ch)curl_close($ch);return null;}$bytes=0;curl_setopt_array($ch,[CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>4,CURLOPT_CONNECTTIMEOUT=>15,CURLOPT_TIMEOUT=>180,CURLOPT_WRITEFUNCTION=>static function($ch,string$d)use($fh,&$bytes):int{$bytes+=strlen($d);if($bytes>80*1024*1024)return 0;return fwrite($fh,$d)?:0;}]);$ok=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$mime=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);fclose($fh);if(!$ok||$code<200||$code>=300||$bytes<128){@unlink($dest);return null;}return ['id'=>ad_id('sound'),'kind'=>'audio','role'=>'sound','path'=>$relative,'url'=>ad_public_media_url($relative),'mime'=>$mime?:'audio/mpeg','bytes'=>$bytes,'created_at'=>ad_now()];}
function adsnd_state():array{$s=ad_state_read();$scenes=[];foreach((array)$s['scenes']as$scene){if(!is_array($scene))continue;$shots=[];foreach((array)$s['shots']as$shot)if(is_array($shot)&&(string)($shot['scene_id']??'')===(string)($scene['id']??''))$shots[]=['id'=>(string)$shot['id'],'number'=>$shot['number']??$shot['shot_number']??0,'title'=>(string)($shot['title']??'Shot'),'dialogue_count'=>count((array)($shot['dialogue']??[])),'sound_design'=>adsnd_shot_plan($shot)];$scenes[]=['id'=>(string)$scene['id'],'title'=>(string)($scene['title']??'Scene'),'sound_design'=>adsnd_scene_plan($scene),'shots'=>$shots];}return ['ok'=>true,'configured'=>ad_mock_mode()||ad_env('RUNWAY_API_KEY')!=='','active_scene_id'=>(string)($s['production']['active_scene_id']??($s['scenes'][0]['id']??'')),'scenes'=>$scenes,'pricing'=>['seed_audio_credits_per_second'=>0.25,'minimum_credits'=>5]];}
function adsnd_store_job(array $job):void{ad_state_mutate(function(array$s)use($job):array{$scope=$job['scope'];$id=$job['target_id'];if($scope==='scene'){foreach($s['scenes']as&$x)if(($x['id']??'')===$id){$p=adsnd_scene_plan($x);$p['jobs'][]=$job;$x['sound_design']=$p;break;}unset($x);}else{foreach($s['shots']as&$x)if(($x['id']??'')===$id){$p=adsnd_shot_plan($x);$p['cues'][]=$job;$x['sound_design']=$p;break;}unset($x);}return$s;});}
function adsnd_update_job(string $jobId,callable $fn):array{return ad_state_mutate(function(array$s)use($jobId,$fn):array{foreach($s['scenes']as&$scene){$p=adsnd_scene_plan($scene);$found=false;foreach($p['jobs']as&$j)if(($j['id']??'')===$jobId){$j=$fn($j,$scene);$found=true;if(($j['status']??'')==='completed'&&is_array($j['asset']??null)&&in_array((string)($j['type']??''),['ambience','music'],true))$p[(string)$j['type'].'_asset']=$j['asset'];break;}unset($j);if($found){$scene['sound_design']=$p;$scene['updated_at']=ad_now();return$s;}}unset($scene);foreach($s['shots']as&$shot){$p=adsnd_shot_plan($shot);$found=false;foreach($p['cues']as&$j)if(($j['id']??'')===$jobId){$j=$fn($j,$shot);$found=true;break;}unset($j);if($found){$shot['sound_design']=$p;$shot['updated_at']=ad_now();return$s;}}unset($shot);return$s;});}
function adsnd_fail_job(string $jobId,string $message):array{return adsnd_update_job($jobId,function(array$j)use($message):array{$j['status']='failed';$j['failed_at']=ad_now();$j['error']=$message;return$j;});}

try{
 if($action==='state')ad_json(adsnd_state());
 if($action==='save-scene-plan'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$id=trim((string)($d['scene_id']??''));$next=ad_state_mutate(function(array$s)use($d,$id):array{foreach($s['scenes']as&$scene)if(($scene['id']??'')===$id){$p=adsnd_scene_plan($scene);foreach(['ambience_prompt','music_prompt','music_behavior','mix_notes']as$k)if(array_key_exists($k,$d))$p[$k]=(string)$d[$k];$scene['sound_design']=$p;$scene['updated_at']=ad_now();break;}unset($scene);return$s;});if(!adsnd_find($next['scenes'],$id))ad_json(['ok'=>false,'error'=>'Scene not found.'],404);ad_json(adsnd_state());}
 if($action==='add-cue'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$shotId=trim((string)($d['shot_id']??''));$state=ad_state_read();if(!adsnd_find((array)$state['shots'],$shotId))ad_json(['ok'=>false,'error'=>'Shot not found.'],404);$type=strtolower((string)($d['type']??'sfx'));if(!in_array($type,['sfx','foley'],true))$type='sfx';$prompt=ad_substr(trim((string)($d['prompt']??'')),0,1200);if($prompt==='')ad_json(['ok'=>false,'error'=>'Describe the sound cue.'],422);$cue=['id'=>ad_id('soundcue'),'scope'=>'shot','target_id'=>$shotId,'type'=>$type,'prompt'=>$prompt,'timing_seconds'=>max(0,(float)($d['timing_seconds']??0)),'duration_hint'=>max(.5,min(30,(float)($d['duration_hint']??3))),'status'=>'planned','asset'=>null,'created_at'=>ad_now()];adsnd_store_job($cue);ad_json(adsnd_state());}
 if($action==='generate'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$scope=(string)($d['scope']??'scene');$id=trim((string)($d['target_id']??''));$type=(string)($d['type']??'ambience');$state=ad_state_read();$prompt='';$durationHint=max(1,min(120,(float)($d['duration_hint']??12)));$jobId=trim((string)($d['job_id']??''));if($scope==='scene'){$scene=adsnd_find((array)$state['scenes'],$id);if(!$scene)ad_json(['ok'=>false,'error'=>'Scene not found.'],404);$p=adsnd_scene_plan($scene);$prompt=trim((string)($type==='music'?$p['music_prompt']:$p['ambience_prompt']));if($type==='music'&&trim((string)$p['music_behavior'])!=='')$prompt.='. Music behavior: '.$p['music_behavior'];}else{$shot=adsnd_find((array)$state['shots'],$id);if(!$shot)ad_json(['ok'=>false,'error'=>'Shot not found.'],404);$cue=null;foreach(adsnd_shot_plan($shot)['cues']as$c)if(($c['id']??'')===$jobId){$cue=$c;break;}if(!$cue)ad_json(['ok'=>false,'error'=>'Sound cue not found.'],404);$prompt=(string)$cue['prompt'];$type=(string)$cue['type'];$durationHint=(float)$cue['duration_hint'];}
  if($prompt==='')ad_json(['ok'=>false,'error'=>'Add a sound description first.'],422);$editorialPrompt=($type==='music'?'Instrumental score only, no dialogue or narration. ':($type==='ambience'?'Continuous room tone and environmental ambience, no dialogue or music. ':'Isolated '.$type.' sound effect, no dialogue or music. ')).$prompt.'. Aim for approximately '.$durationHint.' seconds; the final editor may trim or loop this asset.';
  $internalId=$jobId!==''?$jobId:ad_id('soundjob');$record=['id'=>$internalId,'scope'=>$scope,'target_id'=>$id,'type'=>$type,'prompt'=>$prompt,'duration_hint'=>$durationHint,'status'=>'submitted','asset'=>null,'created_at'=>ad_now()];if($scope==='scene')adsnd_store_job($record);
  if(ad_mock_mode()){$asset=['id'=>ad_id('sound'),'kind'=>'audio','role'=>'sound','path'=>'','url'=>'','mime'=>'audio/mpeg','bytes'=>0,'mock'=>true,'created_at'=>ad_now()];adsnd_update_job($internalId,function(array$j)use($asset){$j['status']='completed';$j['asset']=$asset;$j['completed_at']=ad_now();return$j;});ad_json(['ok'=>true,'done'=>true,'state'=>adsnd_state()]);}
  $key=ad_env('RUNWAY_API_KEY');if($key==='')ad_json(['ok'=>false,'error'=>'RUNWAY_API_KEY is not configured.'],409);try{$resp=ad_http_json('POST','https://api.dev.runwayml.com/v1/sound_effect',['Authorization: Bearer '.$key,'Content-Type: application/json','X-Runway-Version: 2024-11-06'],['model'=>'seed_audio','promptText'=>$editorialPrompt,'outputFormat'=>'mp3','sampleRate'=>48000]);$taskId=(string)($resp['id']??'');if($taskId==='')throw new RuntimeException('Runway returned no sound task id.');adsnd_update_job($internalId,function(array$j)use($taskId){$j['provider_task_id']=$taskId;$j['status']='processing';return$j;});ad_json(['ok'=>true,'done'=>false,'job_id'=>$internalId,'task_id'=>$taskId]);}catch(Throwable$e){adsnd_fail_job($internalId,ad_substr($e->getMessage(),0,400));throw$e;}}
 if($action==='poll'&&$_SERVER['REQUEST_METHOD']==='POST'){$d=ad_json_input();$jobId=trim((string)($d['job_id']??''));$state=ad_state_read();$found=null;foreach((array)$state['scenes']as$s)foreach(adsnd_scene_plan((array)$s)['jobs']as$j)if(($j['id']??'')===$jobId){$found=$j;break 2;}if(!$found)foreach((array)$state['shots']as$s)foreach(adsnd_shot_plan((array)$s)['cues']as$j)if(($j['id']??'')===$jobId){$found=$j;break 2;}if(!$found)ad_json(['ok'=>false,'error'=>'Sound job not found.'],404);if(in_array((string)($found['status']??''),['completed','failed'],true))ad_json(['ok'=>true,'done'=>true,'failed'=>(string)($found['status']??'')==='failed','state'=>adsnd_state()]);$taskId=(string)($found['provider_task_id']??'');if($taskId===''){$message='Provider task id missing.';adsnd_fail_job($jobId,$message);ad_json(['ok'=>false,'error'=>$message],409);}$key=ad_env('RUNWAY_API_KEY');try{$resp=ad_http_json('GET','https://api.dev.runwayml.com/v1/tasks/'.rawurlencode($taskId),['Authorization: Bearer '.$key,'X-Runway-Version: 2024-11-06']);$status=strtoupper((string)($resp['status']??'PENDING'));if($status==='FAILED'){$message=(string)($resp['failure']??'Sound generation failed.');adsnd_fail_job($jobId,$message);ad_json(['ok'=>true,'done'=>true,'failed'=>true,'state'=>adsnd_state()]);}if($status!=='SUCCEEDED')ad_json(['ok'=>true,'done'=>false,'status'=>strtolower($status)]);$out=$resp['output']??[];$url=is_array($out)?(string)($out[0]??''):'';$asset=$url!==''?adsnd_download($url,$taskId):null;if(!$asset){$message='Sound completed but audio could not be saved.';adsnd_fail_job($jobId,$message);ad_json(['ok'=>false,'error'=>$message],502);}adsnd_update_job($jobId,function(array$j)use($asset){$j['status']='completed';$j['asset']=$asset;$j['completed_at']=ad_now();$j['error']=null;return$j;});ad_json(['ok'=>true,'done'=>true,'state'=>adsnd_state()]);}catch(Throwable$e){adsnd_fail_job($jobId,ad_substr($e->getMessage(),0,400));throw$e;}}
 ad_json(['ok'=>false,'error'=>'Unknown sound-design action.'],404);
}catch(Throwable$e){ad_json(['ok'=>false,'error'=>ad_substr($e->getMessage(),0,400)],500);}
