<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';

$action=(string)($_GET['action']??'state');
function adtl_find(array $items,string $id):?array{foreach($items as$x)if(is_array($x)&&(string)($x['id']??'')===$id)return$x;return null;}
function adtl_take_url(array $take):string{if(is_array($take['local']??null)&&!empty($take['local']['url']))return(string)$take['local']['url'];return(string)($take['remote_url']??$take['output_url']??'');}
function adtl_take_path(array $take):string{if(is_array($take['local']??null)&&!empty($take['local']['path']))return AD_ROOT.'/'.ltrim((string)$take['local']['path'],'/');return'';}
function adtl_default(array $state):array{
 $clips=[];foreach((array)$state['scenes']as$scene){foreach((array)($scene['shot_ids']??[])as$shotId){$shot=adtl_find((array)$state['shots'],(string)$shotId);if(!$shot)continue;$takes=array_values(array_filter((array)$state['takes'],static fn($t)=>is_array($t)&&(string)($t['shot_id']??'')===(string)$shotId));$take=end($takes);if(!$take)continue;$clips[]=['id'=>ad_id('tlclip'),'shot_id'=>(string)$shotId,'take_id'=>(string)($take['id']??''),'scene_id'=>(string)($scene['id']??''),'trim_in'=>0.0,'trim_out'=>null,'transition'=>'cut','transition_seconds'=>0.0,'enabled'=>true];}}
 return ['version'=>1,'clips'=>$clips,'tracks'=>['dialogue_gain_db'=>0.0,'ambience_gain_db'=>-8.0,'music_gain_db'=>-12.0,'sfx_gain_db'=>-4.0,'dialogue_ducking_db'=>-8.0,'fade_in_seconds'=>0.25,'fade_out_seconds'=>0.35],'updated_at'=>ad_now()];
}
function adtl_plan(array $state):array{$p=is_array($state['timeline']??null)?$state['timeline']:adtl_default($state);$p['clips']=array_values(array_filter((array)($p['clips']??[]),'is_array'));$d=adtl_default($state)['tracks'];$p['tracks']=array_merge($d,is_array($p['tracks']??null)?$p['tracks']:[]);return$p;}
function adtl_clip_view(array $state,array $clip):array{$shot=adtl_find((array)$state['shots'],(string)($clip['shot_id']??''));$take=adtl_find((array)$state['takes'],(string)($clip['take_id']??''));$scene=adtl_find((array)$state['scenes'],(string)($clip['scene_id']??($shot['scene_id']??'')));$dialogue=[];foreach((array)($shot['dialogue']??[])as$l)if(is_array($l))$dialogue[]=['speaker_name'=>(string)($l['speaker_name']??'Speaker'),'text'=>(string)($l['text']??''),'audio'=>(array)($l['audio_reference']??[])];$sound=is_array($shot['sound_design']??null)?$shot['sound_design']:[];$sceneSound=is_array($scene['sound_design']??null)?$scene['sound_design']:[];return array_merge($clip,['shot_number'=>$shot['number']??$shot['shot_number']??0,'shot_title'=>(string)($shot['title']??'Shot'),'scene_title'=>(string)($scene['title']??'Scene'),'video_url'=>$take?adtl_take_url($take):'','video_local_path'=>$take?adtl_take_path($take):'','duration_target'=>(float)($shot['duration_target']??5),'dialogue'=>$dialogue,'shot_sfx'=>array_values(array_filter((array)($sound['cues']??[]),'is_array')),'scene_ambience'=>(array)($sceneSound['ambience_asset']??[]),'scene_music'=>(array)($sceneSound['music_asset']??[])]);}
function adtl_state():array{$s=ad_state_read();$p=adtl_plan($s);$clips=[];foreach($p['clips']as$c)$clips[]=adtl_clip_view($s,$c);$ffmpeg=adtl_ffmpeg();return['ok'=>true,'timeline'=>['version'=>$p['version']??1,'clips'=>$clips,'tracks'=>$p['tracks'],'updated_at'=>$p['updated_at']??null],'ffmpeg_available'=>$ffmpeg!=='','render_mode'=>$ffmpeg!==''?'server-hard-cuts':'manifest-only'];}
function adtl_ffmpeg():string{foreach(['/usr/bin/ffmpeg','/usr/local/bin/ffmpeg']as$p)if(is_executable($p))return$p;if(function_exists('shell_exec')){$x=trim((string)@shell_exec('command -v ffmpeg 2>/dev/null'));if($x!==''&&is_executable($x))return$x;}return'';}
function adtl_save(array $data):array{return ad_state_mutate(function(array$s)use($data):array{$p=adtl_plan($s);if(isset($data['clips'])&&is_array($data['clips'])){$clips=[];foreach($data['clips']as$c){if(!is_array($c))continue;$shotId=trim((string)($c['shot_id']??''));$takeId=trim((string)($c['take_id']??''));if(!adtl_find((array)$s['shots'],$shotId)||!adtl_find((array)$s['takes'],$takeId))continue;$clips[]=['id'=>(string)($c['id']??ad_id('tlclip')),'shot_id'=>$shotId,'take_id'=>$takeId,'scene_id'=>(string)($c['scene_id']??''),'trim_in'=>max(0,(float)($c['trim_in']??0)),'trim_out'=>isset($c['trim_out'])&&$c['trim_out']!==null?max(0,(float)$c['trim_out']):null,'transition'=>in_array((string)($c['transition']??'cut'),['cut','crossfade'],true)?(string)$c['transition']:'cut','transition_seconds'=>max(0,min(2,(float)($c['transition_seconds']??0))),'enabled'=>!array_key_exists('enabled',$c)||!empty($c['enabled'])];}$p['clips']=$clips;}if(isset($data['tracks'])&&is_array($data['tracks']))foreach(['dialogue_gain_db','ambience_gain_db','music_gain_db','sfx_gain_db','dialogue_ducking_db','fade_in_seconds','fade_out_seconds']as$k)if(array_key_exists($k,$data['tracks']))$p['tracks'][$k]=(float)$data['tracks'][$k];$p['updated_at']=ad_now();$s['timeline']=$p;return$s;});}
function adtl_manifest(array $state):array{$p=adtl_plan($state);$clips=[];$cursor=0.0;foreach($p['clips']as$c){if(empty($c['enabled']))continue;$v=adtl_clip_view($state,$c);$dur=max(.1,(float)$v['duration_target']-(float)$c['trim_in']);if($c['trim_out']!==null)$dur=max(.1,(float)$c['trim_out']-(float)$c['trim_in']);$v['timeline_start']=$cursor;$v['timeline_duration']=$dur;$cursor+=$dur;$clips[]=$v;}return['version'=>1,'duration_seconds'=>$cursor,'clips'=>$clips,'tracks'=>$p['tracks'],'generated_at'=>ad_now()];}
try{
 if($action==='state')ad_json(adtl_state());
 if($action==='reset'&&$_SERVER['REQUEST_METHOD']==='POST'){$next=ad_state_mutate(function(array$s):array{$s['timeline']=adtl_default($s);return$s;});ad_json(adtl_state());}
 if($action==='save'&&$_SERVER['REQUEST_METHOD']==='POST'){adtl_save(ad_json_input());ad_json(adtl_state());}
 if($action==='manifest'){$s=ad_state_read();ad_json(['ok'=>true,'manifest'=>adtl_manifest($s)]);}
 if($action==='render'&&$_SERVER['REQUEST_METHOD']==='POST'){
  $ff=adtl_ffmpeg();if($ff==='')ad_json(['ok'=>false,'error'=>'FFmpeg is not available on this server. The timeline is saved and export-ready, but server rendering is disabled.'],409);$s=ad_state_read();$m=adtl_manifest($s);if(!$m['clips'])ad_json(['ok'=>false,'error'=>'Timeline has no enabled clips.'],422);foreach($m['clips']as$c)if((string)$c['video_local_path']===''||!is_file((string)$c['video_local_path']))ad_json(['ok'=>false,'error'=>'Server render currently requires locally downloaded generated takes.'],409);
  $dir=AD_STORAGE_DIR.'/results';if(!is_dir($dir))@mkdir($dir,0755,true);$list=$dir.'/timeline_'.bin2hex(random_bytes(5)).'.txt';$lines=[];foreach($m['clips']as$c)$lines[]="file '".str_replace("'","'\\''",(string)$c['video_local_path'])."'";file_put_contents($list,implode("\n",$lines));$out=$dir.'/final_'.gmdate('Ymd_His').'_'.bin2hex(random_bytes(3)).'.mp4';$cmd=escapeshellarg($ff).' -y -f concat -safe 0 -i '.escapeshellarg($list).' -c:v libx264 -preset medium -crf 20 -c:a aac -b:a 192k -movflags +faststart '.escapeshellarg($out).' 2>&1';$log=(string)@shell_exec($cmd);@unlink($list);if(!is_file($out)||filesize($out)<1024)ad_json(['ok'=>false,'error'=>'FFmpeg render failed.','detail'=>ad_substr($log,0,600)],500);$rel='storage/results/'.basename($out);ad_json(['ok'=>true,'url'=>ad_public_media_url($rel),'path'=>$rel,'note'=>'Current server renderer produces hard-cut picture assembly. Timeline audio mix and crossfades remain in the saved manifest for the next render phase.']);
 }
 ad_json(['ok'=>false,'error'=>'Unknown timeline action.'],404);
}catch(Throwable$e){ad_json(['ok'=>false,'error'=>ad_substr($e->getMessage(),0,500)],500);}
